#!/bin/bash

# EzCMS Installer - Easy Cloud Minecraft Server
# Minecraft 1.21.1 Vanilla Server for DigitalOcean
# Made with ❤️ by @WhAnci

set -e

cat << "EOF"
╔═══════════════════════════════════════════════════╗
║                                                   ║
║              EzCMS Installer v1.0                 ║
║     Easy Cloud Minecraft Server Setup             ║
║                                                   ║
║     Minecraft 1.21.1 Vanilla + Java 21            ║
║     Made with ❤️ by @WhAnci                       ║
║                                                   ║
╚═══════════════════════════════════════════════════╝
EOF

echo ""
echo "🚀 Starting installation..."
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "❌ Please run as root (use sudo)"
    exit 1
fi

# Update system
echo "📦 Updating system packages..."
apt-get update -qq

# Install Java 21
echo "☕ Installing Java 21..."
apt-get install -y openjdk-21-jre-headless wget screen > /dev/null 2>&1

# Verify Java installation
if ! command -v java &> /dev/null; then
    echo "❌ Java installation failed"
    exit 1
fi

echo "✅ Java 21 installed: $(java -version 2>&1 | head -n 1)"

# Create minecraft user and directory
echo "📁 Creating minecraft directory..."
if ! id "minecraft" &>/dev/null; then
    useradd -r -m -U -d /opt/minecraft -s /bin/bash minecraft
fi

MC_DIR="/opt/minecraft/server"
mkdir -p $MC_DIR
cd $MC_DIR

# Download Minecraft server
echo "⬇️  Downloading Minecraft 1.21.1 server..."
wget -q --show-progress https://piston-data.mojang.com/v1/objects/59353fb40c36d304f2035d51e7d6e6baa98dc05c/server.jar -O server.jar

if [ ! -f "server.jar" ]; then
    echo "❌ Failed to download server.jar"
    exit 1
fi

echo "✅ Server downloaded successfully"

# Accept EULA
echo "📝 Accepting EULA..."
echo "eula=true" > eula.txt

# Create server.properties with optimized settings
echo "⚙️  Creating server configuration..."
cat > server.properties << 'PROPERTIES'
# Minecraft server properties
# Generated by EzCMS
motd=§6EzCMS Server §f- §bPowered by DigitalOcean
server-port=25565
gamemode=survival
difficulty=normal
max-players=20
view-distance=10
simulation-distance=10
pvp=true
enable-command-block=false
spawn-protection=16
max-world-size=29999984
online-mode=true
allow-flight=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
generate-structures=true
white-list=false
enforce-whitelist=false
level-name=world
level-seed=
level-type=minecraft\:normal
PROPERTIES

# Create start script
echo "🔧 Creating start script..."
cat > $MC_DIR/start.sh << 'STARTSCRIPT'
#!/bin/bash
cd /opt/minecraft/server
java -Xmx2G -Xms1G -jar server.jar nogui
STARTSCRIPT

chmod +x $MC_DIR/start.sh

# Create systemd service
echo "🔧 Creating systemd service..."
cat > /etc/systemd/system/minecraft.service << 'SERVICE'
[Unit]
Description=Minecraft Server (EzCMS)
After=network.target

[Service]
Type=simple
User=minecraft
WorkingDirectory=/opt/minecraft/server
ExecStart=/opt/minecraft/server/start.sh
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
SERVICE

# Set permissions
chown -R minecraft:minecraft /opt/minecraft

# Configure firewall
echo "🔥 Configuring firewall..."
if command -v ufw &> /dev/null; then
    ufw allow 25565/tcp > /dev/null 2>&1
    echo "✅ Firewall configured (port 25565 opened)"
else
    echo "⚠️  UFW not found, please open port 25565 manually"
fi

# Enable and start service
echo "🎮 Starting Minecraft server..."
systemctl daemon-reload
systemctl enable minecraft.service > /dev/null 2>&1
systemctl start minecraft.service

# Wait a bit for server to start
sleep 3

# Check if server is running
if systemctl is-active --quiet minecraft.service; then
    echo ""
    echo "╔═══════════════════════════════════════════════════╗"
    echo "║                                                   ║"
    echo "║          ✅ Installation Complete! ✅              ║"
    echo "║                                                   ║"
    echo "╚═══════════════════════════════════════════════════╝"
    echo ""
    echo "📌 Server Status: RUNNING"
    echo "📌 Server IP: $(curl -s ifconfig.me):25565"
    echo ""
    echo "🎮 Useful Commands:"
    echo "   sudo systemctl status minecraft    # Check status"
    echo "   sudo systemctl stop minecraft      # Stop server"
    echo "   sudo systemctl restart minecraft   # Restart server"
    echo "   sudo journalctl -u minecraft -f    # View logs"
    echo ""
    echo "📁 Server files: /opt/minecraft/server"
    echo "⚙️  Edit settings: /opt/minecraft/server/server.properties"
    echo ""
    echo "💡 First time? You might need to wait 1-2 minutes for world generation!"
    echo ""
    echo "⭐ Like this project? Star us on GitHub!"
    echo "   https://github.com/WhAnci/EzCMS"
    echo ""
else
    echo "❌ Server failed to start. Check logs with:"
    echo "   sudo journalctl -u minecraft -n 50"
    exit 1
fi